import i1 from '@/assets/books/o-segredo-de-natalia/osdn-1.jpg'
import i2 from '@/assets/books/o-segredo-de-natalia/osdn-2.jpg'
import i3 from '@/assets/books/o-segredo-de-natalia/osdn-3.jpg'
import i4 from '@/assets/books/o-segredo-de-natalia/osdn-4.jpg'
import i5 from '@/assets/books/o-segredo-de-natalia/osdn-5.jpg'
import i6 from '@/assets/books/o-segredo-de-natalia/osdn-6.jpg'
import i7 from '@/assets/books/o-segredo-de-natalia/osdn-7.jpg'
import i8 from '@/assets/books/o-segredo-de-natalia/osdn-8.jpg'
import i9 from '@/assets/books/o-segredo-de-natalia/osdn-9.jpg'
import i10 from '@/assets/books/o-segredo-de-natalia/osdn-10.jpg'
import i11 from '@/assets/books/o-segredo-de-natalia/osdn-11.jpg'
import i12 from '@/assets/books/o-segredo-de-natalia/osdn-12.jpg'
import i13 from '@/assets/books/o-segredo-de-natalia/osdn-13.jpg'
import i14 from '@/assets/books/o-segredo-de-natalia/osdn-14.jpg'
import i15 from '@/assets/books/o-segredo-de-natalia/osdn-15.jpg'
import i16 from '@/assets/books/o-segredo-de-natalia/osdn-16.jpg'
import i17 from '@/assets/books/o-segredo-de-natalia/osdn-17.jpg'
import i18 from '@/assets/books/o-segredo-de-natalia/osdn-18.jpg'
import i19 from '@/assets/books/o-segredo-de-natalia/osdn-19.jpg'
import i20 from '@/assets/books/o-segredo-de-natalia/osdn-20.jpg'
import i21 from '@/assets/books/o-segredo-de-natalia/osdn-21.jpg'
import i22 from '@/assets/books/o-segredo-de-natalia/osdn-22.jpg'
import i23 from '@/assets/books/o-segredo-de-natalia/osdn-23.jpg'
import i24 from '@/assets/books/o-segredo-de-natalia/osdn-24.jpg'

const images = [
  {id: 1, src: i1, w: 760, h: 531, alt: '<p>[O Lago dos Cisnes]</p><p>O Segredo de Natália</p><p>Prémio Revelação APE/IPLB 1998 de literatura para a infância e a juventude</p><p>Texto: António Laginha</p><p>Ilustrações: Rafaela Mapril</p><p>DIFEL</p>'},
  {id: 2, src: i2, w: 760, h: 531, alt: '<p>O Segredo de Natália.</p><p>(O Lago dos Cisnes contado às crianças).</p><p>Prémio Revelação APE/IPLB 1998 de literatura para a infância e a juventude.</p><p>Texto: António Laginha.</p><p>Ilustrações: Rafaela Mapril.</p>'},
  {id: 3, src: i3, w: 760, h: 531, alt: '<p>A quinta de S. João das Danças era um lugar lindo, bem cuidado, cheio de flores e muitas, muitas árvores de fruto, onde não faltava uma nora que dava água em abundância mesmo nos meses mais quentes do ano...</p><p>Entrava-se por um portão largo em ferro ladeado por duas velhas amendoeiras que, no Inverno, floresciam e perfumavam toda a estrada de terra batida.</p><p>A quinta estava dividida em muitos rectângulos - com uma viçosa laranjeira bem no centro de cada um - e era salpicada com verdura que nascia nos carreirinhos junto das estreitas valas onde corria a água de rega. Havia filas e filas de limoeiros verde-escuro com cachos de limões muito amarelos que pendiam com o peso, dezenas de laranjeiras e algumas pereiras folhudas que se erguiam para o céu...</p>'},
  {id: 4, src: i4, w: 760, h: 531, alt: '<p>O Sr. António lavrava os campos verdes, semeava as tiras de terra limpa de ervas daninhas e encarregava-se das colheitas. D. Rafaela, a sua mulher, cuidava dos filhos, das flores e dos muitos animais que habitavam os estábulos, galinheiros e pocilgas. Cães e gatos viviam junto da casa e eram os que mais brincavam com os filhos do casal, Margarida e Francisco, que quando, ao fim da tarde, voltavam da escola ajudavam a dar de comer às galinhas, patos e perús. Também gostavam muito de assistir à ordenha das ovelhas, cabras e, sobretudo, das vacas.</p>'},
  {id: 5, src: i5, w: 760, h: 531, alt: '<p>Estas davam litros e litros de leite quando se lhes apertava as tetas e mugiam, batiam com os cascos no chão e balançavam o rabo como se o líquido branco que esguichava para dentro dos baldes nada tivesse a ver com elas.</p><p>O dia da matança do porco, geralmente nas manhãs frias de Fevereiro, era dia de festa. A princípio causava o afastamento das crianças pelo medo do facalhão do matador e pelos grunhidos lancinantes do pobre animal mas, depois, elas acabavam por se integrar na azáfama da cozedura da cachola e do sangue, da lavagem das tripas e do enchimento dos chouriços.</p>'},
  {id: 6, src: i6, w: 760, h: 531, alt: '<p>Com excepção dos pobres suinos, todos os animais viviam numa certa paz porque eram criados para ajudar nos trabalhos ou para dar o leite para fazer queijo. Quando uma cabra ou ovelha, de vez em quando, desaparecia do convívio dos outros animais - que as viam sair na carroça puxada pela mula velha - deixava atrás de si um rasto de mistério. Sabia-se que iriam talvez morrer para outras bandas mas nunca tinham tempo para partilhar temores com os amigos. Os murmúrios ficavam, por algum tempo, na boca de todos mas, a pouco e pouco, iam caindo no esquecimento e com tantos coelhos e pintos que nasciam quase todas as semanas, mal dava para recordar os que partiam...</p><p>Muitas eram as histórias que corriam entre a bicharada da quinta de S. João. Umas verdadeiras, outras, simplesmente, inventadas...</p><p>Dizia-se, por exemplo, que os cisnes que nadavam na ribeira que separava a horta das terras dos vizinhos - e que não davam grande importância ao resto dos animais -, não conheciam nem os pais nem a família. Nasceram de uns ovos que uns vizinos ofereceram ao Sr. António e que foram aquecidos por umas potentes lâmpadas dentro de uma mangedoura até as cascas se quebrarem e saírem dois bichos feios e depenados.</p>'},
  {id: 7, src: i7, w: 760, h: 531, alt: '<p>Não tinham quem os aquecesse, por isso foram criados (com desvelo e muito carinho) por um casal de patos até se tornarem nos mais elegantes animais das redondezas. Talvez por isso a sua frieza e distanciação de tudo o que se passava à sua volta!</p><p>Entre todos, o animal mais querido em S. João das Danças era uma enorme e pachorrenta vaca importada da Rússia. D. Natália. Mesmo sem querer, com a sua pelagem lustrosa e avermelhada e os seus conselhos sábios, ela era a verdadeira alma dos estábulos. Veio para dar leite, mas o seu porte distinto e o mistério do seu passado (que só o Sr. António conhecia) logo despertaram o interesse em toda a bicharada.</p><p>A pouco e pouco Natália foi levantando o véu das muitas dúvidas que cobriam o seu passado. As suas histórias, contadas com sotaque de outra terra, deixavam os filhotes de todos os animais de boca aberta...</p><p>Ela era um poço sem fundo, de onde saíam os mais belos contos quando estava inspirada.</p><p>Um dia, sem ninguém imaginar, ao abrirem as portas do estábulo a surpresa foi geral pois Natália - ou Natacha, de seu nome verdadeiro - decidira acabar com todas as dúvidas. É que ela não era, realmente, uma simples vaca!</p>'},
  {id: 8, src: i8, w: 760, h: 531, alt: '<p>Durante a noite pendurara nas paredes tudo o que trouxera na sua bagagem. Na longa viagem carregara apenas um baú antigo, que mantivera fechado a cadeado, e de onde, finalmente, tirara uma dúzia de pinturas cercadas por belíssimas molduras douradas. Lá estava ela, bem mais jovem, a grande bailarina de todos os teatros do mundo: Natália Vacarova.</p>'},
  {id: 9, src: i9, w: 760, h: 531, alt: '<p>Em muitas telas apresentava-se acompanhada pelo marido (e dedicado par no palco), o não menos famoso Mikhail Boishnykov, com quem, no auge das suas carreiras, dera a volta à Terra.. Do outro lado da cerca, a tia Natália, como era carinhosamente tratada, pastava devagar e sem se importar com nada do que se bichanava debaixo dos palheiros. Mas o sossego durou pouco.</p>'},
  {id: 10, src: i10, w: 760, h: 531, alt: '<p>[O Lago dos Cisnes]</p>'},
  {id: 11, src: i11, w: 760, h: 531, alt: '<p>Enquanto os pais ficaram comentando aquelas coisas sem importância que toda a gente gosta de atirar para o ar para ver se acerta na verdade, os filhotes correram para junto de Natália e, em coro, berraram:</p><p>Conta, conta, conta...</p><p>Conta tudo!</p><p>A vaca, enxotando as moscas com a cauda, abanou a cabeça lentamente e, levantando os chifres retorcidos, falou para o grupo de bichos saltitantes:</p><p>- Se ficarem quietos e sentados, posso contar-vos uma história de que eu muito gosto e que viví vezes sem conta. Olhem aquele quadro ali.</p><p>Todos se acotovelaram um pouco, fizeram um círculo meio desajeitado e esticaram os narizes bem para cima para ouvir melhor.</p><p>E Natália começou:</p><p>... num reino antigo de montanhas, florestas e lagos, era uma vez um príncipe que vivia no seu castelo...</p><p>Menino mimado pela mãe que, com todo o cuidado, lhe ensinara a ler e a escrever e por um tutor que lhe dava lições na arte de caçar, na ausência do pai, perdido em terras longínquas. Chamava-se Siegfried e passava o tempo a cavalgar com os amigos por caminhos sem fim.</p>'},
  {id: 12, src: i12, w: 760, h: 531, alt: '<p>Ao aproximar-se a idade adulta, a mãe começou a insistir para que escolhesse mulher para ter filhos.</p><p>Era preciso assegurar a sucessão e quem mandasse nas vastas terras trabalhadas por muitos dos seus súbditos.</p><p>No dia do seu 18<sup>o</sup> aniversário e na presença de muitos aldeões que tinham vindo ao palácio trazendo consigo toda a espécie de presentes para desejar-lhe felicidade e longa vida, a rainha-mãe presenteou-o com o mais esperado de todos eles: uma rica besta cravejada de pedras preciosas. Na condição de que, no dia seguinte, Siegried escolhesse, entre as mais belas convidadas, uma noiva num grande baile organizado em sua honra.</p><p>O príncipe, sempre a sonhar com caçadas e montarias, responde-lhe afirmativamente mas logo manda chamar os seus amigos mais chegados e convida-os para uma saída em direcção à floresta...</p><p>Esquecendo por momentos a promessa que fizera à mãe e o dever de procurar esposa, aponta o céu escurecido por um bando de aves que voa na direcção das montanhas.</p><p>Um grupo de cisnes sobrevoa o maior dos lagos.</p>'},
  {id: 13, src: i13, w: 760, h: 531, alt: '<p>Os rapazes espalham-se pelas margens e Siegfried, mais afoito, desce do deu belo cavalo negro. Sorrateiro, avança sozinho em direcção ao local onde as aves parecem poisar.</p><p>De repente, atrás de si, ouve-se um estranho som de asas esvoaçantes. O príncipe esconde-se entre os arbustos e aponta a sua besta. Porém, em vez de um cisne, surge-lhe uma linda mulher de corpo branco, longos braços ondulantes e olhar melancólico.</p><p>O jovem aproxima-se mas a misteriosa visão recua temerosa e, receando pela própria vida, implora-lhe que afaste a arma.</p><p>Siegfried, perto da bela Odete, ouve-a confessar ser a rainha de todos os cisnes do lago, jovens roubadas das casas de seus pais por um velho feiticeiro que as mantém prisioneiras do seu encanto. Aos primeiros raios da aurora transformam-se em cisnes que vagueiam pelos céus e, apenas ao cair da noite, voltam à sua condição humana podendo, então, dançar no lago cujas águas foram engrossadas com as lágrimas de suas mães. Guardadas noite e dia pelo pérfido feiticeiro, elas só podem ser salvas pelo amor sincero de um jovem mancebo que jurasse amor eterno à mais bonita delas e seja capaz de dar a vida por esse amor.</p>'},
  {id: 14, src: i14, w: 760, h: 531, alt: '<p>Extasiado com a beleza da jovem cativa e tocado com a sua sina, Siegfried diz-lhe ser ela a mulher que, até então, nunca encontrara. Na presença das muitas raparigas que, alegremente, dançam à volta de Odete, ele segura-lhe a mão e pede-lhe que o deixe amá-la.</p><p>A rainha dos cisnes responde-lhe que é perigoso falarem ali de amor, pois o Barão de Rothbart pode aparecer a qualquer instante. Mas ele responde-lhe que não tem medo e jura-lhe que só com ela gostaria de casar.</p><p>Por entre as sombras do luar as negras asas do feiticeiro aparecem por cima de uns rochedos interrompendo o apaixonado encontro de Odete e Siegfried. Este, assustado, aponta uma flecha ao génio do mal mas Odete correndo protege o corpo do seu carcereiro e diz-lhe que não atire pois se ele morresse o encanto nunca se quebraria e elas nunca seriam libertadas</p>'},
  {id: 15, src: i15, w: 760, h: 531, alt: '...'},
  {id: 16, src: i16, w: 760, h: 531, alt: '...'},
  {id: 17, src: i17, w: 760, h: 531, alt: '<p>O valente príncipe acede e o Barão de Rothbart desaparece por entre o arvoredo. Odete segue-o, mas não sem antes Siegfried lhe pedir que vá ao seu baile de aniversário no dia seguinte.</p><p>Sem conseguir acreditar em tão fantástico "sonho" e ainda com o pensamento em Odete, o jovem príncipe vê chegar alguns companheiros que o julgam perdido, trazendo pela rédea o seu imponente cavalo negro.</p><p>No dia seguinte ao cair da noite sobre o palácio real, a rainha-mãe sentada no trono recebe os muitos convidados para o baile de máscaras enquanto o jovem apaixonado não deixa de pensar na visão de Odete. Seis ricas princesas, oriundas de outros tantos países, são-lhe apresentadas por sua mãe na esperança de que, ao privar com cada uma delas, ele se apaixone pela mais bonita e a peça em casamento.</p>'},
  {id: 18, src: i18, w: 760, h: 531, alt: '<p>Depois de muitas danças, reverências e brindes à saúde de todos os presentes, já noite cerrada e quando os festejos já estão quase a terminar, Siegfried - que mal deu atenção às suas solícitas pretendentes - espera ansiosamente a vinda da rainha-cisne feita mulher.</p><p>No momento preciso em que a mãe olha para ele como que a perguntar se já escolhera esposa, as trombetas interromperam a doce música que ecoa pelos salões para anunciar a visita de um nobre desconhecido acompanhado pela sua filha. Todos param com espanto, até a rainha, a quem o inesperado visitante pede para que a filha e o seu séquito participem nos festejos. Siegfried fica petrificado.</p><p>A jovem perante os seus olhos, toda vestida de negro e com penas esvoaçantes, só pode ser Odete. Ela sorrí-lhe e o coração do príncipe não cabe dentro do peito</p>'},
  {id: 19, src: i19, w: 760, h: 531, alt: '<p>Depois de várias danças em que a bela mulher-cisne seduz e inebria o príncipe - incentivada pelo pai que não deixa por um segundo de seguir o súbito romance - chega a hora por todos esperada: a da escolha da noiva.</p><p>Siegfried julgando esta perante a mesma mulher que conhecera no lago comunica a sua mãe que a decisão está tomada e aponta para a jovem de negro.</p><p>Atrás dos vidros de uma das janelas do palácio, Odete, que entretanto chegara, tenta que o príncipe a veja acenando em patético desespero. Siegfried não percebe que está a ser enganado. O pérfido pai do «cisne negro» distrai propositadamente os convidados com as vistosas danças dos seus exóticos acompanhantes e, com gestos hipnóticos, impede que os apelos de Odete sejam vistos por Siegfried e evitem que o seu bem amado esqueça o juramento do lago. Quando a rainha pede ao pai a sua altiva filha em casamento, este exige que o enfeitiçado jovem faça, perante os convivas, um juramento de fidelidade à noiva escolhida.</p>'},
  {id: 20, src: i20, w: 760, h: 531, alt: '<p>Siegfried entusiasmado promete solenemente que desposará aquela que tanto o fascina mas logo, com risos sarcásticos e gestos vingativos, os intrusos revelam a verdadeira identidade: o Barão de Rothbart e a sua filha Odília.</p><p>Finalmente, apercebendo-se o príncipe da presença de Odete no exterior do palácio, e em desespero, tenta seguí-la para lhe pedir perdão, mas é impedido pelo barão que antes de abandonar o palácio com o seu séquito, triunfante e perante o espanto dos presentes, lhe lembra que é a Odília e não a Odete a quem ele está ligado para o resto da vida.</p>'},
  {id: 21, src: i21, w: 760, h: 531, alt: '<p>O alvoroço é total, a rainha desmaia, os convidados não sabem o que fazer e Siegfried enlouquecido, desprezando as ameaças do Barão de Rothbart, corre atrás da sombra branca da sua verdadeira amada.</p><p>De volta ao lago as raparigas-cisne esperavam ansiosas por Odete pressentindo que algo de trágico se tinha passado.</p><p>Quando ela chega conta-lhes que o malvado Barão engendrou uma cilada que fez com que Siegfried quebrasse o seu voto de amor eterno pondo fim ao sonho de tão desejado amor.</p>'},
  {id: 22, src: i22, w: 760, h: 531, alt: '<p>Doravante, Odete e todas elas estariam condenadas a ficar eternamente prisioneiras do seu encanto e das águas do lago.</p><p>Desesperada com o imprudente acto do príncipe, ela apenas encontrará alívio para a sua dor nos líquidos braços da morte. Quando Siegfried, perturbado e inconsolável, aparece sobre um rochedo, implora-lhe o seu perdão. Nesse mesmo momento o Barão de Rothbart faz rebentar uma violenta tempestade para amedrontar o príncipe, mas em vez disso e sabendo que apenas a morte os libertará do seu trágico destino, Siegfried fere mortalmente o mágico.</p><p>Seguidamente, os dois amantes lançam-se para as águas do lago entrelaçados num abraço eterno que os levar à terra da felicidade eterna.</p><p>As águas revoltas acalmam-se e, como por milagre, as jovens libertas do génio do mal olham ternamente os vultos da sua rainha e do formoso príncipe que, lentamente e de mãos dadas, se afastam para sempre...</p>'},
  {id: 23, src: i23, w: 760, h: 531, alt: '...'},
  {id: 24, src: i24, w: 760, h: 531, alt: '<p>Natália estava feliz mas com a voz emocionada.</p><p>Tantas recordações de um tempo que já não volta. Tantos amigos que ficaram pelo caminho. Tantas palmas que já soam distantes.</p><p>Uma incómoda lágrima turvou os olhos daquela que fez sentir o amor e deu beleza a milhares de pessoas. Que dançou histórias alegres e tristes tendo vivido anos e anos para a sua arte.</p><p>Alguns filhotes dos animais da quinta adormeceram ao longo da narrativa, talvez sonhando com a magia que Natália trazia aos seus pobres corações de bichos do campo.</p><p>Outros recolheram lentamente ao curral.</p><p>Os mais próximos de Natália foram descendo, um após o outro, os belos quadros enquanto a grande «ballerina» olhando o fundo do baú via toda uma orquestra que tocava para si comovente e apaixonada a bela música de Tchaikovsky.</p>'}
]

export default images
