const quotes = [
  {title: 'Nunca escrevo prefácios. Mas, desta vez, abri uma excepção', author: 'Jorge Listopad', text: '<p>(…) com António Laginha, porém, a música toca diferente. Sabe voar no trapézio. Sabe agarrar a verdade à qual Lisboa não está habituada. É a excepção. É excepção em vários aspectos: enumero alguns. Ao que pude saber, era e é bom professor de matérias inseguras; para ser bom pedagogo dessas indisciplinadas disciplinas, deve ser-se inconformista com imaginação, poeta que se apropria do rigor; não temer as inerentes dificuldades, as ditas “broncas”. Além disso, é vocacionado crítico de dança que sabe e, além do saber, é sensível e, além da sensibilidade, exerce a verdade, admitamos, a sua verdade, porém, séria e argumentada. Homo eticus. Custe o que custar. Conjugar todas essas características é difícil. Assim vai-não-vai a honrada vida do crítico de dança.</p><p>(…) seja calmo ma non troppo, seja como é, precisamos de Laginhas assim, continue.</p>', in: 'In <em>Prefácio de Pontos com Vista</em> (António Laginha, Sinapis Editores, Lisboa 2015)'},
  {title: 'António Laginha, um bailarino desassossegado', author: 'Guiomar Belo Marques', text: '<p>António Laginha tem-se obstinado em viver de modo harmonioso. Um verdadeiro poço de energia. Apesar de se ter licenciado em arquitectura o bailado tem preenchido a sua vida. A dança é o seu pulsar.</p>', in: '(2001, Agosto). António Laginha, um bailarino desassossegado. Boletim 30 Dias, Câmara Municipal de Oeiras, p. 7-10.'},
  {title: 'Fundador e Director do Centro de Dança de Oeiras', author: 'Maria Iben Hammer', text: '<p>António Laginha é um homem entusiasta e enérgico, com um currículo tão sólido como a muralha da China. Bailarino, coreógrafo e fundador do <a target="_blank" href="http://cdo.com.pt">Centro de Dança de Oeiras</a>. O CDO é apenas o topo de uma lista, que contém outras actividades como escritor, produtor e professor - tudo com a dança como fulcro. A dança é simplesmente o que este homem apaixonante e apaixonado tem de melhor.</p>', in: '(2010, Novembro). Uma visita ao Centro de Dança de Oeiras. Revista Terpsichore, Dinamarca, n.p.'},
  {title: '', author: 'Hector Zaraspe', text: '<p>É um excelente professor de dança, extremamente sensível, devotado e do mais alto calibre.</p>', in: 'mestre de bailado e coreógrafo argentino'},
  {title: '', author: 'Clive Barnes', text: '<p>Os escritos de António Laginha manifestam um intenso sentido poético.</p>', in: 'crítico de dança internacional.'}
]

export default quotes
